version: "3"
services:
  intermine_builder:
    container_name: intermine_builder
    image: intermine/builder:latest
    volumes:
      - ./data/mine/data:/home/intermine/intermine/data
      - ./data/mine/configs:/home/intermine/intermine/configs
      # - ./data/mine/[PUT_YOUR_MINE_NAME_HERE]:/home/intermine/intermine/[PUT_YOUR_MINE_NAME_HERE]      
    environment:
      - MINE_NAME=${MINE_NAME}
      - MEM_OPTS=${MEM_OPTS:-"-Xmx2g -Xms1g"}
    depends_on: 
      - postgres
      - solr
      - tomcat

  postgres:
    container_name: intermine_postgres
    image: intermine/postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  solr:
    container_name: intermine_solr
    image: intermine/solr
    environment:
      - MEM_OPTS=${MEM_OPTS:-"-Xmx2g -Xms1g"}
    volumes:
      - ./data/solr:/opt/solr/server/solr/mycores

  tomcat:
    container_name: intermine_tomcat
    image: intermine/tomcat
    environment:
      - MEM_OPTS=${MEM_OPTS:-"-Xmx1g -Xms500m"}
    ports:
      - ${TOMCAT_HOST_PORT:-9999}:${TOMCAT_PORT:-8080}

# volumes:
#   PostgresDBData:
#   SolrDBData:
#   MineData:
#   MineConfigs: